### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Vieriksson** [episodehunter/web#7]
- [x] Add search-bar with RxJS
- [x] Show same poster as everywhere else with a 9-column grid

**Comment by tjoskar** [comment]
There is currently about 6k tv shows in the db. If we only make it possible to search for names we can export all names and ids at a cost of ~140KB (as csv). This makes it possible to include all show-names in the memory at the client side.

– Create a simple job that extracts all names every night or so and put it in a json dump, in a bucket (and cdn)
– When the user visits the site, we download the json dump
– When the user wants to search we can just look at the json dump and perform a blazing fast search (even fuzzy search with a lib like http://fusejs.io/ or https://github.com/bevacqua/fuzzysearch)

Problems:
Q: How to keep the json dump in sync?
A: We just download a new one in the background and replaces the old one.

Q: Can it become a performance problem to parse and search a 140k dump json file?
A: Maybe, in that case, use generators and put it on another thread ((service)worker)

Q: How well google home find a show?
A: We can parse the json dump in a lambda (140KB in a lambda is nothing!) OR we can just access the database directly. We do not need any fuzzy search or autocomplete for google home.
